# Generated by Django 4.2.1 on 2023-05-11 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cohorteTimer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cohorte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('tipo', models.CharField(max_length=250)),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cohorteTimer.programa')),
            ],
        ),
    ]
