# Generated by Django 4.2.1 on 2023-05-11 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cohorteTimer', '0002_cohorte'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfesorCohorte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cohorte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cohorteTimer.cohorte')),
                ('id_profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cohorteTimer.profesor')),
            ],
        ),
    ]
