# Generated by Django 4.2.1 on 2023-05-12 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cohorteTimer', '0004_program_teacher_remove_profesorcohorte_id_cohorte_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cohorte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('kind', models.CharField(max_length=250)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cohorteTimer.program')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherCohorte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cohorte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cohorteTimer.cohorte')),
                ('id_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cohorteTimer.teacher')),
            ],
        ),
    ]
